import styles from "./page.module.css";

const manifesto = [
  {
    title: "Typography Ritual",
    mantra:
      "Set the cadence with fearless pairings. Let ligatures dance and caps whisper in calculated rhythm.",
    detail: "Pair expressive display faces with precision monos to orchestrate contrast.",
  },
  {
    title: "Palette Voltage",
    mantra:
      "Flood the canvas with heat and cool incandescence. Saturation is a spotlight, not wallpaper.",
    detail: "One dominant hue, one rebellious accent, both anchored by unlit voids.",
  },
  {
    title: "Motion Thesis",
    mantra:
      "Animate intent, not noise. Stage a single sweeping reveal and let micro-movements hum in the periphery.",
    detail: "Delay, stagger, and ease—each component joins a choreographed entrance.",
  },
];

const atmospheres = [
  {
    label: "Nocturne Workshop",
    description: "Velvet nebulae, cyan schematics, and slow shutter light trails.",
    tag: "Dark Bloom",
  },
  {
    label: "Analog Neon",
    description: "Paper grain over luminous inks; imperfect grids that breathe.",
    tag: "Tactile Futurism",
  },
  {
    label: "Ceremonial Gradient",
    description: "Ritualistic color melts powered by metallic reflections.",
    tag: "Chromatic Rite",
  },
];

export default function Home() {
  return (
    <main className={styles.canvas}>
      <section className={styles.hero}>
        <span className={styles.badge}>Design Master Prompt</span>
        <h1>
          Choreograph
          <span> the unexpected aesthetic.</span>
        </h1>
        <p>
          Draft prompts that refuse the ordinary. Fuse typography lore, color voltages, and motion rituals to
          summon visuals that feel authored—never autogenerated.
        </p>
        <div className={styles.actions}>
          <a
            className={styles.primary}
            href="#manifesto"
          >
            Compose a prompt
          </a>
          <a
            className={styles.secondary}
            href="#atmospheres"
          >
            Decode aesthetics
          </a>
        </div>
      </section>

      <section
        id="manifesto"
        className={styles.manifesto}
      >
        <header className={styles.sectionHeader}>
          <span>01</span>
          <h2>Prompt choreography manifesto</h2>
        </header>
        <div className={styles.cards}>
          {manifesto.map((item) => (
            <article
              key={item.title}
              className={styles.card}
            >
              <h3>{item.title}</h3>
              <p className={styles.mantra}>{item.mantra}</p>
              <p className={styles.detail}>{item.detail}</p>
            </article>
          ))}
        </div>
      </section>

      <section
        id="atmospheres"
        className={styles.atmospheres}
      >
        <header className={styles.sectionHeader}>
          <span>02</span>
          <h2>Atmosphere archetypes</h2>
        </header>
        <div className={styles.moodboard}>
          {atmospheres.map((item) => (
            <div
              key={item.label}
              className={styles.mood}
            >
              <div className={styles.moodHalo} />
              <div className={styles.moodCore}>
                <span className={styles.moodTag}>{item.tag}</span>
                <h3>{item.label}</h3>
                <p>{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className={styles.timeline}>
        <header className={styles.sectionHeader}>
          <span>03</span>
          <h2>Staging the reveal</h2>
        </header>
        <ol className={styles.steps}>
          <li>
            <span className={styles.stepLabel}>1. Prime the void</span>
            <p>
              Begin with negative space and ambient gradients. Define the emotional bias before any elements take the
              stage.
            </p>
          </li>
          <li>
            <span className={styles.stepLabel}>2. Cue the hero</span>
            <p>
              Introduce the centerpiece with a delayed crescendo—blur to focus, scale to settle. Actions deserve theatre.
            </p>
          </li>
          <li>
            <span className={styles.stepLabel}>3. Release supporting casts</span>
            <p>
              Stagger feature cards, reveal copy with mono flourishes, and let accent glyphs orbit to imply depth.
            </p>
          </li>
        </ol>
      </section>
    </main>
  );
}
